### ISSUE TITLE
Fetch Failure

### ISSUE THREAD

**Issue by Jernee** [DrakiaXYZ/SPT-LiveFleaPriceDB#1]
Getting this error one startup intermittently.

ModLoader: Error when loading async mod: fetch failed
TypeError: fetch failed
    at node:internal/deps/undici/undici:12345:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Function.updatePrices (/opt/server/user/mods/DrakiaXYZ-LiveFleaPrices/src/mod.ts:60:30)
    at Mod.postDBLoadAsync (/opt/server/user/mods/DrakiaXYZ-LiveFleaPrices/src/mod.ts:37:14)
    at PostDBModLoader.executeModsAsync (/snapshot/src/loaders/PostDBModLoader.ts:63:21)
    at PostDBModLoader.onLoad (/snapshot/src/loaders/PostDBModLoader.ts:31:13)
    at App.load (/snapshot/src/utils/App.ts:58:13)

**Comment by Jernee** [comment]
Oops I think this is the wrong repository.

**Comment by DrakiaXYZ** [comment]
https://github.com/DrakiaXYZ/SPT-LiveFleaPrices/issues/2
